package view;


import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author PC-PC
 */
public class TheQuest6 extends javax.swing.JFrame {

       private static int RespostaAleatoria;
       
       private static File[] pasta = new File[20];
       private static File[] resposta = new File[20];
       
       String alou = System.getProperty("user.home");

    public static int getRespostaAleatoria() {
        return RespostaAleatoria;
    }

    public static void setRespostaAleatoria(int RespostaAleatoria) {
        TheQuest6.RespostaAleatoria = RespostaAleatoria;
    }
    /**
     * Creates new form TheQuest
     */
    public TheQuest6() {
        initComponents();
        txPrayer.setText(TheGame.getNickName());
        txPontos.setText(""+TheGame.getPontos());
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txPrayer = new javax.swing.JLabel();
        txPontos = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbPergunta2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("Prayer:");

        jLabel2.setForeground(new java.awt.Color(0, 0, 255));
        jLabel2.setText("Pontos:");

        jLabel3.setText("Perguntas");

        lbPergunta2.setText("<html>Mais Um daquelas coisas que eu só estou fazendo para ver se consigo mesmo, bom, ao clicar no botão a resposta aparecerá no seu pc</html>");
        lbPergunta2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                troll(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                destrolando(evt);
            }
        });

        jButton1.setText("Criar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextField1.setText("resposta");

        jButton2.setText("ok");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txPrayer, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txPontos)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField1)
                            .addComponent(lbPergunta2, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(54, 54, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txPrayer)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txPontos)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(lbPergunta2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addContainerGap(117, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void troll(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_troll
        // TODO add your handling code here:
        
    }//GEN-LAST:event_troll

    private void destrolando(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_destrolando
       
    }//GEN-LAST:event_destrolando

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

      
      
      
       Random tw = new Random();
       int test = tw.nextInt(pasta.length);
      
       
       Random tw2 = new Random();
        
       int respostaRw = tw2.nextInt(999999999);
       
       setRespostaAleatoria(respostaRw);
        for (int i = 0; i < pasta.length; i++) {
            pasta[i] = new File (alou + "\\Desktop\\GudiLoki"+i+"\\sera\\que\\eh\\essa");
            pasta[i].mkdirs();
        
        
        
       
        
        
       
            
            if (i == test) {
            resposta[i] = new File(alou +"\\Desktop\\GudiLoki"+test+"\\sera\\que\\eh\\essa\\Resposta.txt");
            try {
                resposta[i].createNewFile();
                
                FileWriter fileWriter  = new FileWriter(resposta[i]);
               BufferedWriter writer = new BufferedWriter(fileWriter); 
               
               writer.write(""+respostaRw);
               
               writer.close();
               fileWriter.close();
            } catch (IOException ex) {
                System.out.println("deu ruim na resposta"+test);
            }
        }
            else{
            resposta[i] = new File(alou +"\\Desktop\\GudiLoki"+i+"\\sera\\que\\eh\\essa\\Errou.txt");
            try {
                resposta[i].createNewFile();
                
                FileWriter fileWriter  = new FileWriter(resposta[i]);
               BufferedWriter writer = new BufferedWriter(fileWriter); 
               
               writer.write("Errado");
               
               writer.close();
               fileWriter.close();
            } catch (IOException ex) {
                System.out.println("deu ruim na errada "+test);
            }
        }
            
        
        
        }
        
        JOptionPane.showMessageDialog(null, "Caso não tenho reparado ainda,olhe sua area de trabalho(espero que tenho funcionado)");
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if (Integer.parseInt(jTextField1.getText()) == getRespostaAleatoria()) {
            
            TheGame.setPontos(+60);
            
            DeletaGeral();
            new TheQuest7().setVisible(true);
            dispose();
        }
        else{
            new TheGameOver().setVisible(true);
            DeletaGeral();
            dispose();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

       private void DeletaGeral(){
           for (int i = 0; i < pasta.length; i++) {
                              
               resposta[i].delete();
               
               pasta[i] = new File(alou +"\\Desktop\\GudiLoki"+i+"\\sera\\que\\eh\\essa");
               pasta[i].delete();
               
               pasta[i] = new File(alou +"\\Desktop\\GudiLoki"+i+"\\sera\\que\\eh");
               pasta[i].delete();
               
               pasta[i] = new File(alou +"\\Desktop\\GudiLoki"+i+"\\sera\\que");
               pasta[i].delete();
               
               pasta[i] = new File(alou +"\\Desktop\\GudiLoki"+i+"\\sera");
               pasta[i].delete();
               
               pasta[i] = new File(alou+"\\Desktop\\GudiLoki"+i);
               pasta[i].delete();
           }
       }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TheQuest1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TheQuest1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TheQuest1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TheQuest1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TheQuest1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lbPergunta2;
    private javax.swing.JLabel txPontos;
    private javax.swing.JLabel txPrayer;
    // End of variables declaration//GEN-END:variables
}
